spring:
  sleuth:
    traceId128: true
    supportsJoin: false
  application:
    name: transfer-api
  datasource:
    username: user
    url: jdbc:mysql://localhost:3306/db
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    password: guest
    port: '5672'
    host: localhost
    notifyTransactionExchange: notify_transaction
    notifyTransactionQueue: q_notify_transaction
    username: guest

management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
